version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_backend:
    working_directory: ~/circleci/Backend/
    executor: node/default
    steps:
      - checkout:
          path: ~/circleci/
      - run:
          command: ls
      - node/install:
          node-version: '16.13'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - node/install-packages:
          app-dir: ~/circleci/Backend/
          cache-path: node_modules
          override-ci-command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_frontend:
    working_directory: ~/circleci/Frontend/
    executor: node/default
    steps:
      - checkout:
          path: ~/circleci/
      - run:
          command: ls
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - node/install-packages:
          app-dir: ~/circleci/Frontend/
          cache-path: node_modules
          override-ci-command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_backend:
    working_directory: ~/circleci/Backend/
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Backend Test
          command: npm test

  lint_backend:
    working_directory: ~/circleci/Backend/
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Backend Lint Test
          command: npm run lint

  lint_frontend:
    working_directory: ~/circleci/Frontend/
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Frontend Lint Test
          command: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_backend
      - test_backend:
          requires:
            - build_backend
      - lint_backend:
          requires:
            - build_backend
      - build_frontend
