version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build_backend:
    working_directory: ~/circleci/Backend/
    executor: node/default
    steps:
      - checkout:
          path: ~/circleci/
      - run:
          command: ls
      - node/install-npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - node/install-packages:
          app-dir: ~/circleci/Backend/
          cache-path: node_modules
          override-ci-command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  test_backend:
    working_directory: ~/circleci/Backend/
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Backend Test
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_backend
      - test_backend:
          requires:
            - build_backend
